GET http://localhost:3000/sanity

###



###

POST http://localhost:3000/authServer
Content-Type: application/json

{
    "username": "Kyle"
}

###

GET http://localhost:3000/authServer

###

GET http://localhost:3000/houses/sanity